/** Static list for combobox search (v0). Extend as needed. */
export const tunisLocations: string[] = [
  "Tunis",
  "La Marsa",
  "Carthage",
  "Sidi Bou Said",
  "Le Bardo",
  "La Goulette",
  "Ariana",
  "Ben Arous",
  "Manouba",
  "Beni Khalled",
  "Nabeul",
  "Hammamet",
  "Sousse",
  "Monastir",
  "Mahdia",
  "Sfax",
  "Bizerte",
  "Béja",
  "Jendouba",
  "Kairouan",
  "Gabès",
];
