import type {
  AdvancedDivision,
  AdvancedLineItemTemplate,
  AdvancedMarkups,
  AdvancedProjectInput,
  LocationZone,
} from "./types";

export const ADVANCED_DIVISIONS: AdvancedDivision[] = [
  {
    id: "structure",
    name: "Gros œuvre / structure",
    description: "Fondations, ossature, dalles et éléments porteurs.",
  },
  {
    id: "masonry",
    name: "Maçonnerie / béton",
    description: "Murs, chapes, enduits de base et reprises béton.",
  },
  {
    id: "electricity",
    name: "Électricité",
    description: "Courant fort, courant faible et mise aux normes.",
  },
  {
    id: "plumbing",
    name: "Plomberie / sanitaires",
    description: "Réseaux sanitaires, évacuations et équipements.",
  },
  {
    id: "fluids",
    name: "Chauffage, climatisation, fluides",
    description: "Climatisation, chauffage et réseaux techniques.",
  },
  {
    id: "joinery",
    name: "Menuiserie aluminium / bois",
    description: "Menuiseries extérieures, portes, placards et bois.",
  },
  {
    id: "insulation",
    name: "Étanchéité / isolation",
    description: "Toitures, terrasses, isolation et protections.",
  },
  {
    id: "finishes",
    name: "Peinture / décoratifs",
    description: "Revêtements, peinture, carrelage et finitions.",
  },
  {
    id: "outdoor",
    name: "Aménagements extérieurs",
    description: "Piscine, jardin, clôtures, terrasses et accès.",
  },
];

export const ADVANCED_LINE_TEMPLATES: AdvancedLineItemTemplate[] = [
  {
    id: "site-installation",
    divisionId: "structure",
    description: "Installation chantier, implantation et sécurité",
    unit: "forfait",
    costType: "equipment",
    budgetShare: 0.035,
    quantity: () => 1,
    offers: ["grosOeuvre", "premium", "luxe"],
  },
  {
    id: "foundations",
    divisionId: "structure",
    description: "Fondations, longrines et béton armé",
    unit: "m²",
    costType: "material",
    budgetShare: 0.18,
    quantity: (surfaceM2) => surfaceM2,
    offers: ["grosOeuvre", "premium", "luxe"],
  },
  {
    id: "frame",
    divisionId: "structure",
    description: "Poteaux, poutres, dalles et escaliers",
    unit: "m²",
    costType: "labor",
    budgetShare: 0.19,
    quantity: (surfaceM2) => surfaceM2,
    offers: ["grosOeuvre", "premium", "luxe"],
  },
  {
    id: "masonry-walls",
    divisionId: "masonry",
    description: "Maçonnerie, cloisons et enduits de base",
    unit: "m²",
    costType: "labor",
    budgetShare: 0.105,
    quantity: (surfaceM2) => Math.round(surfaceM2 * 1.35),
    offers: ["grosOeuvre", "premium", "luxe"],
  },
  {
    id: "waterproofing",
    divisionId: "insulation",
    description: "Étanchéité toiture terrasse et isolation",
    unit: "m²",
    costType: "subcontractor",
    budgetShare: 0.045,
    quantity: (surfaceM2) => Math.round(surfaceM2 * 0.45),
    offers: ["premium", "luxe"],
  },
  {
    id: "electrical",
    divisionId: "electricity",
    description: "Tableaux, gaines, câblage et appareillage",
    unit: "m²",
    costType: "subcontractor",
    budgetShare: 0.075,
    quantity: (surfaceM2) => surfaceM2,
    offers: ["premium", "luxe"],
  },
  {
    id: "plumbing",
    divisionId: "plumbing",
    description: "Réseaux plomberie, évacuation et sanitaires",
    unit: "lot",
    costType: "subcontractor",
    budgetShare: 0.065,
    quantity: () => 1,
    offers: ["premium", "luxe"],
  },
  {
    id: "hvac",
    divisionId: "fluids",
    description: "Climatisation, chauffage et réseaux fluides",
    unit: "m²",
    costType: "subcontractor",
    budgetShare: 0.06,
    quantity: (surfaceM2) => surfaceM2,
    offers: ["luxe"],
  },
  {
    id: "aluminium",
    divisionId: "joinery",
    description: "Menuiserie aluminium, vitrage et portes",
    unit: "m²",
    costType: "material",
    budgetShare: 0.085,
    quantity: (surfaceM2) => Math.round(surfaceM2 * 0.28),
    offers: ["premium", "luxe"],
  },
  {
    id: "flooring",
    divisionId: "finishes",
    description: "Revêtements sols, faïence et plinthes",
    unit: "m²",
    costType: "material",
    budgetShare: 0.09,
    quantity: (surfaceM2) => surfaceM2,
    offers: ["premium", "luxe"],
  },
  {
    id: "paint",
    divisionId: "finishes",
    description: "Peinture intérieure, décoratifs et retouches",
    unit: "m²",
    costType: "labor",
    budgetShare: 0.045,
    quantity: (surfaceM2) => Math.round(surfaceM2 * 2.8),
    offers: ["premium", "luxe"],
  },
  {
    id: "outdoor-basic",
    divisionId: "outdoor",
    description: "Terrasse, accès, clôture et jardin de base",
    unit: "forfait",
    costType: "subcontractor",
    budgetShare: 0.025,
    quantity: () => 1,
    offers: ["premium", "luxe"],
  },
];

export const LOCATION_ZONE_LABELS: Record<LocationZone, string> = {
  grandTunis: "Grand Tunis",
  coastal: "Zones côtières",
  interior: "Intérieur du pays",
  south: "Sud tunisien",
};

export const LOCATION_OPTIONS: Array<{ label: string; zone: LocationZone }> = [
  { label: "Tunis", zone: "grandTunis" },
  { label: "Ariana", zone: "grandTunis" },
  { label: "La Marsa", zone: "grandTunis" },
  { label: "Sousse", zone: "coastal" },
  { label: "Monastir", zone: "coastal" },
  { label: "Hammamet", zone: "coastal" },
  { label: "Sfax", zone: "coastal" },
  { label: "Bizerte", zone: "coastal" },
  { label: "Kairouan", zone: "interior" },
  { label: "Beja", zone: "interior" },
  { label: "Gafsa", zone: "interior" },
  { label: "Djerba", zone: "south" },
  { label: "Gabès", zone: "south" },
  { label: "Tozeur", zone: "south" },
];

export const DEFAULT_ADVANCED_PROJECT: AdvancedProjectInput = {
  style: "moderne",
  buildType: "r1",
  offer: "premium",
  surfaceM2: 220,
  location: "Tunis",
  zone: "grandTunis",
  terrain: "oui",
  options: {
    pool: false,
    basement: false,
    garden: false,
  },
  optionSurfaces: {
    poolM2: 32,
    basementM2: 60,
    gardenM2: 80,
  },
};

export const DEFAULT_ADVANCED_MARKUPS: AdvancedMarkups = {
  overhead: 0.08,
  profit: 0.1,
  contingency: 0.07,
  tax: 0,
};
